# Generated by Django 2.2.4 on 2020-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200620_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='tz',
            field=models.CharField(max_length=8),
        ),
    ]
